[package]
name = "ks-plugin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
ks-plugin-shared.workspace = true
ks-plugin-external.workspace = true
ks-plugin-api.workspace = true

[lints]
workspace = true
