Unicode true

!include "MUI2.nsh"
!include "LogicLib.nsh"
!include "nsDialogs.nsh"
!include "x64.nsh"

!define DISPLAY_NAME "Plugin ký số"
!define EXE_NAME "Ký số plugin.exe"
!define UNINSTALLER_NAME "go-cai-dat.exe"
!define INSTALL_DIR_NAME "KySoPlugin"
!define PUBLISHER "YnaP"

!define CONFIG_KEY "Software\KySoPlugin"
!define ENVIRONMENT_VALUE "MoiTruong"
!define INSTALL_DIR_VALUE "ThuMucCai"
!define AUTOSTART_KEY "Software\Microsoft\Windows\CurrentVersion\Run"
!define AUTOSTART_NAME "KySoPlugin"
!define UNINSTALL_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\KySoPlugin"

!define PROVIDER_KEY "SOFTWARE\Microsoft\Cryptography\Defaults\Provider"
!define SILENT_FLAG "/S"
!define MSI_SILENT_FLAGS "/qn /norestart"

!ifndef BIT4ID_SETUP_EXT
  !define BIT4ID_SETUP_EXT ".exe"
!endif

!ifndef TOKEN_MANAGER_SETUP_EXT
  !define TOKEN_MANAGER_SETUP_EXT ".exe"
!endif

; Generated by dong-goi.ps1 from vendor/<folder>/tham-so.txt; defines *_SETUP_ARGS.
!ifdef VENDOR_ARGS_INCLUDE
  !include "${VENDOR_ARGS_INCLUDE}"
!endif

!ifndef BIT4ID_SETUP_ARGS
  !if "${BIT4ID_SETUP_EXT}" == ".msi"
    !define BIT4ID_SETUP_ARGS "${MSI_SILENT_FLAGS}"
  !else
    !define BIT4ID_SETUP_ARGS "${SILENT_FLAG}"
  !endif
!endif

!ifndef TOKEN_MANAGER_SETUP_ARGS
  !if "${TOKEN_MANAGER_SETUP_EXT}" == ".msi"
    !define TOKEN_MANAGER_SETUP_ARGS "${MSI_SILENT_FLAGS}"
  !else
    !define TOKEN_MANAGER_SETUP_ARGS "${SILENT_FLAG}"
  !endif
!endif

; An .msi must go through msiexec: "/S" is an NSIS switch and an .msi renamed to .exe does not run at all.
; Arguments are backtick-quoted because they may contain double quotes (InstallShield: /s /v"/qn").
!macro RunVendorSetup FILE EXT ARGS
  !if "${EXT}" == ".msi"
    ExecShellWait "runas" "msiexec.exe" `/i "${FILE}" ${ARGS}`
  !else
    ExecShellWait "runas" "${FILE}" `${ARGS}`
  !endif
!macroend

!ifndef VERSION
  !define VERSION "3.0.0"
!endif

!ifndef VERSION_FULL
  !define VERSION_FULL "3.0.0.0"
!endif

!ifndef PLUGIN_EXE
  !define PLUGIN_EXE "ks.plugin.api\bin\Release\net9.0-windows\${EXE_NAME}"
!endif

!ifndef OUTPUT_FILE
  !define OUTPUT_FILE "${EXE_NAME}"
!endif

!ifndef BST_CHECKED
  !define BST_CHECKED 1
!endif

Name "${DISPLAY_NAME} ${VERSION}"
OutFile "${OUTPUT_FILE}"
InstallDir "$LOCALAPPDATA\${INSTALL_DIR_NAME}"
InstallDirRegKey HKCU "${CONFIG_KEY}" "${INSTALL_DIR_VALUE}"
RequestExecutionLevel user
SetCompressor /SOLID lzma
ShowInstDetails show
ShowUninstDetails show
BrandingText "${DISPLAY_NAME} ${VERSION}"

VIProductVersion "${VERSION_FULL}"
VIAddVersionKey "ProductName" "${DISPLAY_NAME}"
VIAddVersionKey "FileDescription" "Bộ cài ${DISPLAY_NAME}"
VIAddVersionKey "FileVersion" "${VERSION_FULL}"
VIAddVersionKey "ProductVersion" "${VERSION}"
VIAddVersionKey "CompanyName" "${PUBLISHER}"
VIAddVersionKey "LegalCopyright" "© 2026 ${PUBLISHER}"

Var Environment
Var RadioProduction
Var RadioStaging
Var RadioDevelopment

!define MUI_ICON "ks.plugin.api\Assets\ky-so.ico"
!define MUI_UNICON "ks.plugin.api\Assets\ky-so.ico"
!define MUI_ABORTWARNING

!define MUI_WELCOMEPAGE_TITLE "Cài ${DISPLAY_NAME}"
!define MUI_WELCOMEPAGE_TEXT "Plugin làm cầu nối giữa trang web ký số và USB token.$\r$\n$\r$\nTrình cài đặt sẽ cài các trình điều khiển token máy còn thiếu (token bit4id và token đời cũ trước 2022), chép plugin vào thư mục bạn chọn và bật tự khởi động cùng Windows.$\r$\n$\r$\nBấm Next để bắt đầu."

!define MUI_DIRECTORYPAGE_TEXT_TOP "Chọn thư mục lưu plugin và dữ liệu của nó. Mặc định nằm trong hồ sơ người dùng nên không cần quyền quản trị."

!define MUI_FINISHPAGE_TITLE "Đã cài xong"
!define MUI_FINISHPAGE_TEXT "${DISPLAY_NAME} đã được cài và sẽ tự khởi động cùng Windows.$\r$\n$\r$\nQuay lại trang ký số và bấm Kiểm tra lại."
!define MUI_FINISHPAGE_RUN "$INSTDIR\${EXE_NAME}"
!define MUI_FINISHPAGE_RUN_TEXT "Chạy ${DISPLAY_NAME} ngay"

!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_DIRECTORY
Page custom EnvironmentPage EnvironmentPageLeave
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

!insertmacro MUI_LANGUAGE "Vietnamese"

LangString ^BackBtn ${LANG_VIETNAMESE} "< &Back"
LangString ^NextBtn ${LANG_VIETNAMESE} "&Next >"
LangString ^CancelBtn ${LANG_VIETNAMESE} "Cancel"
LangString ^InstallBtn ${LANG_VIETNAMESE} "&Install"
LangString ^UninstallBtn ${LANG_VIETNAMESE} "&Uninstall"
LangString ^CloseBtn ${LANG_VIETNAMESE} "&Close"
LangString ^BrowseBtn ${LANG_VIETNAMESE} "B&rowse..."
LangString ^ShowDetailsBtn ${LANG_VIETNAMESE} "Show &details"

Function .onInit
  SetRegView 64
  SetShellVarContext current
  StrCpy $Environment "Production"
FunctionEnd

Function un.onInit
  SetRegView 64
  SetShellVarContext current
FunctionEnd

Function EnvironmentPage
  !insertmacro MUI_HEADER_TEXT "Môi trường chạy" "Chọn môi trường plugin dùng khi khởi động."

  nsDialogs::Create 1018
  Pop $0
  ${If} $0 == error
    Abort
  ${EndIf}

  ${NSD_CreateLabel} 0 0 100% 28u "Lựa chọn này được ghi vào registry và plugin đọc lại làm ASPNETCORE_ENVIRONMENT mỗi lần khởi động. Máy người dùng cuối chọn Production."
  Pop $0

  ${NSD_CreateRadioButton} 8u 34u 95% 12u "Production — máy người dùng cuối"
  Pop $RadioProduction

  ${NSD_CreateRadioButton} 8u 50u 95% 12u "Staging — môi trường kiểm thử"
  Pop $RadioStaging

  ${NSD_CreateRadioButton} 8u 66u 95% 12u "Development — máy lập trình viên"
  Pop $RadioDevelopment

  ${If} $Environment == "Staging"
    ${NSD_SetState} $RadioStaging ${BST_CHECKED}
  ${ElseIf} $Environment == "Development"
    ${NSD_SetState} $RadioDevelopment ${BST_CHECKED}
  ${Else}
    ${NSD_SetState} $RadioProduction ${BST_CHECKED}
  ${EndIf}

  nsDialogs::Show
FunctionEnd

Function EnvironmentPageLeave
  ${NSD_GetState} $RadioStaging $0
  ${If} $0 == ${BST_CHECKED}
    StrCpy $Environment "Staging"
    Return
  ${EndIf}

  ${NSD_GetState} $RadioDevelopment $0
  ${If} $0 == ${BST_CHECKED}
    StrCpy $Environment "Development"
    Return
  ${EndIf}

  StrCpy $Environment "Production"
FunctionEnd

; In: $R6 = provider name prefix. Out: $R0 = "1" when registered.
Function FindProvider
  StrCpy $R0 "0"
  StrLen $R7 $R6
  StrCpy $R1 0

  ${Do}
    EnumRegKey $R2 HKLM "${PROVIDER_KEY}" $R1
    ${If} $R2 == ""
      ${ExitDo}
    ${EndIf}
    IntOp $R1 $R1 + 1

    StrCpy $R3 $R2 $R7
    ${If} $R3 == $R6
      StrCpy $R0 "1"
      ${ExitDo}
    ${EndIf}
  ${Loop}
FunctionEnd

; In: $R6 = file pattern in System32. Out: $R0 = "1" when found.
Function FindSystemFile
  StrCpy $R0 "0"

  ${If} ${RunningX64}
    ${DisableX64FSRedirection}
  ${EndIf}

  FindFirst $R4 $R5 "$SYSDIR\$R6"
  ${If} $R5 != ""
    StrCpy $R0 "1"
  ${EndIf}
  FindClose $R4

  ${If} ${RunningX64}
    ${EnableX64FSRedirection}
  ${EndIf}
FunctionEnd

Function DetectBit4id
  StrCpy $R6 "bit4id"
  Call FindProvider
  ${If} $R0 == "0"
    StrCpy $R6 "bit4xpki"
    Call FindProvider
  ${EndIf}
  ${If} $R0 == "0"
    StrCpy $R6 "bit4*.dll"
    Call FindSystemFile
  ${EndIf}
FunctionEnd

Function DetectTokenManager
  StrCpy $R6 "eToken"
  Call FindProvider
  ${If} $R0 == "0"
    StrCpy $R6 "eTOKCSP.dll"
    Call FindSystemFile
  ${EndIf}
FunctionEnd

Function InstallBit4id
  Call DetectBit4id
  ${If} $R0 == "1"
    DetailPrint "Trình điều khiển token bit4id: máy đã có sẵn, bỏ qua."
    Return
  ${EndIf}

!ifdef BIT4ID_SETUP
  DetailPrint "Trình điều khiển token bit4id: chưa có, đang cài. Xin chấp nhận hộp thoại nâng quyền."
  InitPluginsDir
  File "/oname=$PLUGINSDIR\bit4id-setup${BIT4ID_SETUP_EXT}" "${BIT4ID_SETUP}"
  !insertmacro RunVendorSetup "$PLUGINSDIR\bit4id-setup${BIT4ID_SETUP_EXT}" "${BIT4ID_SETUP_EXT}" `${BIT4ID_SETUP_ARGS}`

  Call DetectBit4id
  ${If} $R0 == "1"
    DetailPrint "Trình điều khiển token bit4id: cài xong."
  ${Else}
    DetailPrint "Trình điều khiển token bit4id: CHƯA cài được. Plugin vẫn chạy nhưng sẽ không thấy chứng thư trên token bit4id."
  ${EndIf}
!else
  DetailPrint "Trình điều khiển token bit4id: bản cài này không kèm sẵn. Lấy bộ cài từ đơn vị cấp chứng thư số rồi cài trước."
!endif
FunctionEnd

Function InstallTokenManager
  Call DetectTokenManager
  ${If} $R0 == "1"
    DetailPrint "Trình điều khiển token đời cũ (TokenManager): máy đã có sẵn, bỏ qua."
    Return
  ${EndIf}

!ifdef TOKEN_MANAGER_SETUP
  DetailPrint "Trình điều khiển token đời cũ (TokenManager): chưa có, đang cài. Xin chấp nhận hộp thoại nâng quyền."
  InitPluginsDir
  File "/oname=$PLUGINSDIR\tokenmanager-setup${TOKEN_MANAGER_SETUP_EXT}" "${TOKEN_MANAGER_SETUP}"
  !insertmacro RunVendorSetup "$PLUGINSDIR\tokenmanager-setup${TOKEN_MANAGER_SETUP_EXT}" "${TOKEN_MANAGER_SETUP_EXT}" `${TOKEN_MANAGER_SETUP_ARGS}`

  Call DetectTokenManager
  ${If} $R0 == "1"
    DetailPrint "Trình điều khiển token đời cũ (TokenManager): cài xong."
  ${Else}
    DetailPrint "Trình điều khiển token đời cũ (TokenManager): CHƯA cài được. Plugin vẫn chạy nhưng sẽ không thấy chứng thư trên token đời cũ."
  ${EndIf}
!else
  DetailPrint "Trình điều khiển token đời cũ (TokenManager): bản cài này không kèm sẵn. Tải TokenManager ở dichvucong.ca.gov.vn nếu dùng token trước 2022."
!endif
FunctionEnd

Section "Plugin ký số"
  DetailPrint "Đang dừng bản plugin đang chạy..."
  System::Call 'kernel32::GetCurrentProcessId()i.r0'
  nsExec::ExecToLog 'taskkill /F /IM "${EXE_NAME}" /FI "PID ne $0"'
  Pop $0
  Sleep 500

  Call InstallBit4id
  Call InstallTokenManager

  DetailPrint "Đang chép plugin vào $INSTDIR..."
  SetOutPath "$INSTDIR"
  File "/oname=$INSTDIR\${EXE_NAME}" "${PLUGIN_EXE}"

  WriteRegStr HKCU "${CONFIG_KEY}" "${INSTALL_DIR_VALUE}" "$INSTDIR"
  WriteRegStr HKCU "${CONFIG_KEY}" "${ENVIRONMENT_VALUE}" "$Environment"
  DetailPrint "Môi trường: $Environment"

  WriteRegStr HKCU "${AUTOSTART_KEY}" "${AUTOSTART_NAME}" '"$INSTDIR\${EXE_NAME}"'

  WriteUninstaller "$INSTDIR\${UNINSTALLER_NAME}"

  WriteRegStr HKCU "${UNINSTALL_KEY}" "DisplayName" "${DISPLAY_NAME}"
  WriteRegStr HKCU "${UNINSTALL_KEY}" "DisplayVersion" "${VERSION}"
  WriteRegStr HKCU "${UNINSTALL_KEY}" "Publisher" "${PUBLISHER}"
  WriteRegStr HKCU "${UNINSTALL_KEY}" "DisplayIcon" "$INSTDIR\${EXE_NAME}"
  WriteRegStr HKCU "${UNINSTALL_KEY}" "InstallLocation" "$INSTDIR"
  WriteRegStr HKCU "${UNINSTALL_KEY}" "UninstallString" '"$INSTDIR\${UNINSTALLER_NAME}"'
  WriteRegDWORD HKCU "${UNINSTALL_KEY}" "NoModify" 1
  WriteRegDWORD HKCU "${UNINSTALL_KEY}" "NoRepair" 1
SectionEnd

Section "Uninstall"
  DetailPrint "Đang dừng plugin..."
  nsExec::ExecToLog 'taskkill /F /IM "${EXE_NAME}"'
  Pop $0
  Sleep 500

  DeleteRegValue HKCU "${AUTOSTART_KEY}" "${AUTOSTART_NAME}"
  DeleteRegKey HKCU "${UNINSTALL_KEY}"
  DeleteRegKey HKCU "${CONFIG_KEY}"

  Delete "$INSTDIR\${EXE_NAME}"
  Delete "$INSTDIR\${UNINSTALLER_NAME}"
  RMDir "$INSTDIR"

  DetailPrint "Đã gỡ plugin. Các trình điều khiển token (bit4id, TokenManager) được giữ nguyên vì phần mềm khác còn dùng."
SectionEnd
